Repository freekalmykia/web-dev-club, pull requests merged in 2023-04, with the labels that each got.

#3 Merge main to develop
  README.md
  guides/assets/images/git-1-1.PNG
  guides/assets/images/git-1-10.PNG
  guides/assets/images/git-1-11.PNG
  guides/assets/images/git-1-12.PNG
  guides/assets/images/git-1-13.PNG
  guides/assets/images/git-1-14.PNG
  guides/assets/images/git-1-15.PNG
  guides/assets/images/git-1-16.PNG
  guides/assets/images/git-1-17.PNG
  guides/assets/images/git-1-18.PNG
  guides/assets/images/git-1-19.PNG
  guides/assets/images/git-1-2.PNG
  guides/assets/images/git-1-20.PNG
  guides/assets/images/git-1-21.PNG
  guides/assets/images/git-1-3.PNG
  guides/assets/images/git-1-4.PNG
  guides/assets/images/git-1-5.PNG
  guides/assets/images/git-1-6.PNG
  guides/assets/images/git-1-7.PNG
  guides/assets/images/git-1-8.PNG
  guides/assets/images/git-1-9.PNG
  guides/how-to-write-markdown.md
  markdown-articles/albert/second-amendment.md
Labels: enhancement

#5 nogana: add my first article
  markdown-articles/nogana/my-first-article.md
Labels: documentation

#6 Irina: add my first md article
  markdown-articles/irina/my-article.md
Labels: good first issue
